# Generated by Django 5.2.1 on 2026-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='feedback_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_source',
            field=models.CharField(default='rule-based', max_length=30),
        ),
    ]
