# Generated by Django 5.2.1 on 2026-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0012_assessment_domain_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisedefinition',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exercisetrack',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
