# Generated by Django 5.2.1 on 2026-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0013_alter_exercisedefinition_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetrack',
            name='concept_kicker',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
