# Generated by Django 5.2.1 on 2026-04-11 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_submission_execution_results_and_review_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='arenauser',
            name='xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='unlocked_progress_rewards',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('best_passed_tests', models.PositiveIntegerField(default=0)),
                ('best_total_tests', models.PositiveIntegerField(default=0)),
                ('best_ratio', models.FloatField(default=0)),
                ('first_passed_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_progress_markers', models.JSONField(blank=True, default=list)),
                ('xp_awarded_total', models.PositiveIntegerField(default=0)),
                ('best_progress_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arena.submission')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='arena.exercise')),
                ('first_pass_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arena.submission')),
                ('last_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arena.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_progress', to='arena.arenauser')),
            ],
            options={
                'ordering': ['exercise__title'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
