# Generated by Django 5.2.1 on 2026-04-11 23:03

import django.db.models.deletion
from django.db import migrations, models


def seed_explanations(apps, schema_editor):
    from arena.explanation_builder import build_explanation_blueprint

    Exercise = apps.get_model('arena', 'Exercise')
    ExerciseExplanation = apps.get_model('arena', 'ExerciseExplanation')
    ExerciseExplanationConcept = apps.get_model('arena', 'ExerciseExplanationConcept')
    ExerciseExplanationCodeExample = apps.get_model('arena', 'ExerciseExplanationCodeExample')

    for exercise in Exercise.objects.select_related('track').all():
        blueprint = build_explanation_blueprint(exercise)
        explanation = ExerciseExplanation.objects.create(
            exercise=exercise,
            learning_goal=blueprint.learning_goal,
            concept_focus_markdown=blueprint.concept_focus_markdown,
            reading_strategy_markdown=blueprint.reading_strategy_markdown,
            implementation_strategy_markdown=blueprint.implementation_strategy_markdown,
            assessment_notes_markdown=blueprint.assessment_notes_markdown,
            common_mistakes=blueprint.common_mistakes,
            mastery_checklist=blueprint.mastery_checklist,
        )

        ExerciseExplanationConcept.objects.bulk_create(
            [
                ExerciseExplanationConcept(
                    explanation=explanation,
                    title=concept.title,
                    explanation_text=concept.explanation_text,
                    why_it_matters=concept.why_it_matters,
                    common_mistake=concept.common_mistake,
                    sort_order=index,
                )
                for index, concept in enumerate(blueprint.concepts, start=1)
            ]
        )

        ExerciseExplanationCodeExample.objects.bulk_create(
            [
                ExerciseExplanationCodeExample(
                    explanation=explanation,
                    title=example.title,
                    rationale=example.rationale,
                    language=example.language,
                    code=example.code,
                    sort_order=index,
                )
                for index, example in enumerate(blueprint.code_examples, start=1)
            ]
        )


def unseed_explanations(apps, schema_editor):
    ExerciseExplanation = apps.get_model('arena', 'ExerciseExplanation')
    ExerciseExplanation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0008_backfill_missing_exercise_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_goal', models.TextField(blank=True)),
                ('concept_focus_markdown', models.TextField(blank=True)),
                ('reading_strategy_markdown', models.TextField(blank=True)),
                ('implementation_strategy_markdown', models.TextField(blank=True)),
                ('assessment_notes_markdown', models.TextField(blank=True)),
                ('common_mistakes', models.JSONField(blank=True, default=list)),
                ('mastery_checklist', models.JSONField(blank=True, default=list)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='arena.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseExplanationCodeExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('rationale', models.TextField(blank=True)),
                ('language', models.CharField(default='python', max_length=30)),
                ('code', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_examples', to='arena.exerciseexplanation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseExplanationConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('explanation_text', models.TextField()),
                ('why_it_matters', models.TextField(blank=True)),
                ('common_mistake', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='arena.exerciseexplanation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_explanations, unseed_explanations),
    ]
