# Generated by Django 5.2.1 on 2026-04-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0009_exerciseexplanation_exerciseexplanationcodeexample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('source_kind', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='exercisetrack',
            options={'ordering': ['module__sort_order', 'category__sort_order', 'sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='arenauser',
            name='is_catalog_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='concept_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='estimated_time_minutes',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='exercise',
            name='pedagogical_brief',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='track_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='concept_kicker',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='level_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='milestone_requirement_label',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='milestone_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='milestone_title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.CreateModel(
            name='ExerciseTrackConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('why_it_matters', models.TextField(blank=True)),
                ('common_mistake', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='arena.exercisetrack')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseTrackPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='arena.exercisetrack')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='arena.exercisetype'),
        ),
        migrations.AddField(
            model_name='exercisetrack',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='arena.learningmodule'),
        ),
    ]
